theme: jekyll-theme-minimal
title: Gursimran Sachar
logo: Headshot.jpg
description: Data Analyst | Marketing Analyst | Tech Analyst | Business Analyst
show_downloads: false
links:
  - title: View my Kaggle profile
    url: https://www.kaggle.com/gursimransachar
github:
  is_project_page: false
