theme: jekyll-theme-minimal
title: Gursimran Sachar
logo: Headshot.jpg
description: Data Analyst | Marketing Analyst | Tech Analyst | Business Analyst
show_downloads: false
github:
  is_project_page: false
